CREATE TABLE IF NOT EXISTS comment(
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   user INT NOT NULL,
   city INT NOT NULL,
   text TEXT NOT NULL,
   timestamp DATETIME NOT NULL,
   FOREIGN KEY (user) REFERENCES user(id),
   FOREIGN KEY (city) REFERENCES city(id)
);